//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public string genre { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> Availability { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Pages { get; set; }
    }
}
