//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BiblitekaEntities5 : DbContext
    {
        public BiblitekaEntities5()
            : base("name=BiblitekaEntities5")
        {
        }
     
        private static BiblitekaEntities5 _instance;

      
        public static BiblitekaEntities5 GetContext()
        {
            if (_instance == null) _instance = new BiblitekaEntities5();
            return _instance;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuthPeople> AuthPeople { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<Peoples> Peoples { get; set; }
    }
}
